.\" Manpage for 42sh.
.\" Contact julien.gautier@epita.fr.in to correct errors or typos.
.TH 42sh 1 "07 November 2016" "0.5" "42sh man page"
.SH NAME
42sh \- shell, the standart command language interpreter
.SH SYNOPSIS
42sh
.SH DESCRIPTION
The 42 sh utility is a command language interpreter that shall execute commands
read form a command line string, the standard input, or a specidifed file.
.SH OPTIONS
42sh accept the following options :
-c <command>
.SH BUGS
No known bugs.
.SH AUTHOR
julien.gautier, tourne_v, remaud_a
