.\" Manpage for 42sh.
.\" Contact julien.gautier@epita.fr.in to correct errors or typos.
.TH 42sh 1 "07 November 2016" "0.5" "42sh man page"
.SH NAME
42sh \- shell, the standart command language interpreter
.SH SYNOPSIS
42sh [options] [file]
.SH DESCRIPTION
The 42 sh utility is a command language interpreter that shall execute commands
read form a command line string, the standard input, or a specidifed file. If no
file is given in parameter or the option -c is not used, 42sh is open in
interactive mode.
.SH OPTIONS
42sh accept the following options :
.TP
.BR \-c " <command>"
execute a single command
.TP
.B --norc
: desactivate the ressources header
.TP
.B [+-]O
: -O sets the value of the option and +O unset it
.TP nn
.P
ast-print Create the file ast.dot, which is the dot representation of the AST of the last comand executed
.TP nn
.P
dotglob : If set, 42sh includes filenames beginning with a `.' in the results of pathname expansion
.TP nn
.P
expand_aliases : If set, aliases are expanded as described above under ALIASES. This  option  is enabled by default for interactive shells
.TP nn
.P
extglob : If set, the extended pattern matching features described  above  under Pathname Expansion are enabled
.TP nn
.P
nocaseglob : If set, 42sh matches filenames in a  case-insensitive  fashion when performing pathname expansion
.TP nn
.P
nullglob : If set, 42sh allows patterns which match no files to expand to a null string, rather than themselves
.TP nn
.P
sourcepath : If set, the source (.) builtin uses the value of PATH to find the directory containing the file supplied as an argument. This option is enabled by default
.TP nn
.P
xpg_echo : If set, the echo builtin expands backslash-escape sequences by default

.TP
.B --ast-print
: print the abstract syntax tree generated by the parser
.TP
.B --version
: print the 42sh version
.SH BUGS
No known bugs.
.SH AUTHOR
Julien Gautier (julien.gautier), Vincent Tourneur (tourne_v), Arthur Remaud
(remaud_a)
